move:
  ros__parameters:
    plugins:
      - ros2d2_move_bt_node
    waypoints: ["kitchen", "living_room", "bedroom", "bathroom", "d1_k", "d1_lr", "d2_br", "d2_lr", "d3_br", "d3_bath"]
    waypoint_coords:
      kitchen: [0.0, 1.2]
      living_room: [0.0, -1.12]
      bedroom: [0.0, 0.0]
      bathroom: [0.0, 0.0]
      d1_k: [0.0, 0.5]
      d1_lr: [0.0, 0.0]
      d2_br: [0.0, 0.0]
      d2_lr: [0.0, 0.0]
      d3_br: [0.0, 0.0]
      d3_bath: [0.0, 0.0]
move_through_door:
  ros__parameters:
    plugins:
      - ros2d2_move_through_door_bt_node
    waypoints: ["d1_k", "d1_lr", "d2_br", "d2_lr", "d3_br", "d3_bath"]
    waypoint_coords:
      d1_k: [0.0, 0.0]
      d1_lr: [0.0, 0.0]
      d2_br: [0.0, 0.0]
      d2_lr: [0.0, 0.0]
      d3_br: [0.0, 0.0]
      d3_bath: [0.0, 0.0]
open_door:
  ros__parameters:
    plugins:
      - ros2d2_open_door_bt_node
close_door:
  ros__parameters:
    plugins:
      - ros2d2_close_door_bt_node
drop:
  ros__parameters:
    plugins:
      - ros2d2_drop_bt_node
pick:
  ros__parameters:
    plugins:
      - ros2d2_pick_bt_node
give_object:
  ros__parameters:
    plugins:
      - ros2d2_give_object_bt_node
arrange_object:
  ros__parameters:
    plugins:
      - ros2d2_arrange_object_bt_node
requested_door_closed:
  ros__parameters:
    plugins:
      - ros2d2_requested_door_closed_bt_node
requested_door_opened:
  ros__parameters:
    plugins:
      - ros2d2_requested_door_opened_bt_node