move:
  ros__parameters:
    plugins:
      - ros2d2_move_bt_node
    waypoints: ["kitchen", "living_room", "corridor", "bedroom", "bathroom", "d1_k", "d1_lr", "d2_cr", "d2_lr", "d3_br", "d3_cr", "d4_bath", "d4_br", "d5_house"]
    waypoint_coords:
      kitchen: [0.45, 2.91, 0.0]
      living_room: [1.0, -3.75, 0.0]
      corridor: [-2.19, 0.3, 1.57]
      bedroom: [-4.01, 1.71, 0.0]
      bathroom: [-5.03, -3.27, 0.0]
      d1_k: [-0.32, 0.68, 1.57]
      d1_lr: [-0.37, -0.07, 1.57]
      d2_cr: [-1.84, -1.64, 3.14]
      d2_lr: [-0.70, -1.55, 3.14]
      d3_br: [-3.46, 1.45, 3.14]
      d3_cr: [-2.51, 1.45, 3.14]
      d4_bath: [-5.32, -2.24, 4.71]
      d4_br: [-5.32, -0.86, 4.71]
      d5_house: [-2.27, -4.23, 4.71]
move_through_door:
  ros__parameters:
    plugins:
      - ros2d2_move_through_door_bt_node
    waypoints: ["d1_k", "d1_lr", "d2_cr", "d2_lr", "d3_br", "d3_cr", "d4_bath", "d4_br"]
    waypoint_coords:
      d1_k: [-0.32, 0.68, 1.57]
      d1_lr: [-0.37, -0.07, 1.57]
      d2_cr: [-1.84, -1.64, 3.14]
      d2_lr: [-0.70, -1.55, 3.14]
      d3_br: [-3.46, 1.45, 3.14]
      d3_cr: [-2.51, 1.45, 3.14]
      d4_bath: [-5.32, -2.24, 4.71]
      d4_br: [-5.32, -0.86, 4.71]
open_door:
  ros__parameters:
    plugins:
      - ros2d2_open_door_bt_node
close_door:
  ros__parameters:
    plugins:
      - ros2d2_close_door_bt_node
drop:
  ros__parameters:
    plugins:
      - ros2d2_drop_bt_node
pick:
  ros__parameters:
    plugins:
      - ros2d2_pick_bt_node
give_object:
  ros__parameters:
    plugins:
      - ros2d2_give_object_bt_node
arrange_object:
  ros__parameters:
    plugins:
      - ros2d2_arrange_object_bt_node
requested_door_closed:
  ros__parameters:
    plugins:
      - ros2d2_requested_door_closed_bt_node
requested_door_opened:
  ros__parameters:
    plugins:
      - ros2d2_requested_door_opened_bt_node