name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - test

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install deps popf
        run: sudo apt-get install libfl-dev
        
      - name: Setup ros2
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: humble
          
      - name: Repo plansys2
        run: wget -0 /tmp/all.repos https://raw.githubusercontent.com/IntelligentRoboticsLabs/plansys2_tfd_plan_solver/master/plansys2.repos
        
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: plansys2_gpsr_ros2d2
          target-ros2-distro: humble
          import-token: ${{ secrets.WORKFLOW_TOKEN }}
          vcs-repo-file-url: /tmp/all.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
